### Solicitar tareas
GET http://localhost:5000/api/tareas/

### Solicitar tarea por ID
GET http://localhost:5000/api/tareas/615f141ef2c869a666abfe9e

### Solicitar tareas por ID de usuario
GET http://localhost:5000/api/tareas/usuarios/612d1fa4eff4fb054bd12be3

### Crear una tarea
POST http://localhost:5000/api/tareas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiI2MTVjZTM4NDM5ODE1OTVhMjZkNDNiYWUiLCJlbWFpbCI6InNhbXVlbEBnbWFpbC5jb20iLCJpYXQiOjE2MzQ1NTAwMzYsImV4cCI6MTYzNDU1MzYzNn0.Hu9u4g5ZNXCBijYSWvt2e2K_pAIGX3HgwAnBr3vzshE

{
    "id_usuario": "615ce3843981595a26d43bae",
    "descripcion": "Esto es una nueva tarea con nueva fecha"
}

### Eliminar tarea por ID
DELETE http://localhost:5000/api/tareas/616d412299a700e6fc531664
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiI2MTVjZTM4NDM5ODE1OTVhMjZkNDNiYWUiLCJlbWFpbCI6InNhbXVlbEBnbWFpbC5jb20iLCJpYXQiOjE2MzQ1NTAwMzYsImV4cCI6MTYzNDU1MzYzNn0.Hu9u4g5ZNXCBijYSWvt2e2K_pAIGX3HgwAnBr3vzshE

### Modificar tarea
PATCH http://localhost:5000/api/tareas/615f141ef2c869a666abfe9e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOiI2MTVjZTM4NDM5ODE1OTVhMjZkNDNiYWUiLCJlbWFpbCI6InNhbXVlbEBnbWFpbC5jb20iLCJpYXQiOjE2MzM2MjA5MTcsImV4cCI6MTYzMzYyNDUxN30.lQOqRLX7t-RQaqEt-psWx55xihndXhT1dHyTphuF_5I

{
    "descripcion": "Nueva tarea modificada2",
    "completada": true
}